spec: install ebsnvme in sbindir
this patch fixes the rpmbuild errors because of missing ebsnvme install;

before:
```
$ rpmbuild -bb rpmbuild/SPECS/amazon-ec2-utils.spec
.
.
+ exit 0
Processing files: amazon-ec2-utils-2.2.0-1.amzn2023.noarch
error: File not found: /home/ec2-user/rpmbuild/BUILDROOT/amazon-ec2-utils-2.2.0-1.amzn2023.x86_64/usr/sbin/ebsnvme

RPM build errors:
    File not found: /home/ec2-user/rpmbuild/BUILDROOT/amazon-ec2-utils-2.2.0-1.amzn2023.x86_64/usr/sbin/ebsnvme
```

after:
```
$ rpmbuild -bb rpmbuild/SPECS/amazon-ec2-utils.spec
.
.
+ install -m755 /home/ec2-user/rpmbuild/SOURCES/ebsnvme /home/ec2-user/rpmbuild/BUILDROOT/amazon-ec2-utils-2.2.0-1.amzn2023.x86_64/usr/sbin
.
.
.
+ rm -rf /home/ec2-user/rpmbuild/BUILDROOT/amazon-ec2-utils-2.2.0-1.amzn2023.x86_64
+ RPM_EC=0
++ jobs -p
+ exit 0
```

Signed-off-by: Swapnil Dinkar <sddinkar@amazon.com>